on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: astral-sh/ruff-action@v3
      - run: ruff check .
      - run: ruff format --check .
      - uses: astral-sh/setup-uv@v5
      - name: Run tests
        run: |
          uv venv
          source .venv/bin/activate
          uv sync
          pytest -v
